language: python
sudo: required
env:
  - DOCKER_COMPOSE_VERSION=1.16.1
services:
  - docker
python:
  - "3.6"
script:
  - docker run -it --rm cmarks/py-app-test bash -c 'cd app/ && python3 -m unittest discover -v'
  - docker run -it --rm cmarks/py-app-test bash -c 'cd basicproject/ && python3 -m unittest discover -v'
